### ISSUE TITLE
This package doesn't work with a blank new project for RN 59.10

### ISSUE THREAD

**Issue by manish-jain-1** [react-native-push-notification-ios/push-notification-ios#49]
Steps to reproduce:

https://github.com/manishjain-hrbl/pushnotificationtest2

Run `npx react-native init pushnotificationtest2 --version 0.59.10`

Open above folder in code editor:

Add below to `package.json `
```
"@react-native-community/push-notification-ios": "1.0.2",
"react-native-push-notification": "3.1.3" 

```

(Above step also tried with push 3.1.9)

Run `npm i`

Run `react-native link`

(I created a blank `Podfile` just in case but that didn't matter)

Modify `AppDelegate.m` as per the documentation

Run `react-native run-ios`

(I have also tried clean from xcode>clean and iOS/build delete)

Errors:

Linking pushnotificationtest2

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRNCPushNotificationIOS.a'

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRCTBlob.a'

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRCTAnimation.a'

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRCTActionSheet.a'

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRCTGeolocation.a'

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRCTImage.a'

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRCTLinking.a'

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRCTNetwork.a'

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRCTSettings.a'

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRCTText.a'

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRCTVibration.a'

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRCTWebSocket.a'

▸ Linking pushnotificationtest2

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRNCPushNotificationIOS.a'

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRCTBlob.a'

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRCTAnimation.a'

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRCTActionSheet.a'

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRCTGeolocation.a'

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRCTImage.a'

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRCTLinking.a'

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRCTNetwork.a'

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRCTSettings.a'

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRCTText.a'

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRCTVibration.a'

❌  clang: error: no such file or directory: '/Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Products/Debug-iphonesimulator/libRCTWebSocket.a'

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening pushnotificationtest2.xcworkspace

** BUILD FAILED **

<img width="917" alt="image" src="https://user-images.githubusercontent.com/1090670/70367056-67233680-1851-11ea-9271-0650f5f1cd9b.png">

Old errors that I managed to fix from XCode:

The following build commands failed:
        Ld /Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Intermediates.noindex/pushnotificationtest2.build/Debug-iphonesimulator/pushnotificationtest2.build/Objects-normal/x86_64/Binary/pushnotificationtest2 normal x86_64
        Ld /Users/manishjain/pushnotificationtest2/ios/build/pushnotificationtest2/Build/Intermediates.noindex/pushnotificationtest2.build/Debug-iphonesimulator/pushnotificationtest2.build/Objects-normal/i386/Binary/pushnotificationtest2 normal i386
(2 failures)
. Run CLI with --verbose flag for more details.

 Linking pushnotificationtest2

❌  Undefined symbols for architecture x86_64
> Symbol: _OBJC_CLASS_$_RCTPushNotificationManager
> Referenced from: objc-class-ref in AppDelegate.o

❌  ld: symbol(s) not found for architecture x86_64

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening pushnotificationtest2.xcodeproj

--Confirmed that package works with latest version 0.61.5

To reproduce the issue, download repo: https://github.com/manishjain-hrbl/pushnotificationtest2

**Comment by manish-jain-1** [comment]
So, I was getting this error because I had both old and new PushNotification xcodeproj in my Xcode project. I removed the old one. Added new one again. FYI, I was on Legacy build system.

Changes checked in: https://github.com/manishjain-hrbl/pushnotificationtest2

**Comment by Naturalclar** [comment]
Closing this issue for triaging purpose.
